Description of asciiWrite
Home > utility > asciiWrite.m
asciiWrite
PURPOSE
asciiWrite: Write a matrix as an ascii file
SYNOPSIS
function asciiWrite(mat, fileName, format)
DESCRIPTION
 asciiWrite: Write a matrix as an ascii file
    Usage: asciiWrite(mat, fileName, format)
        format: format string, such as '%d', '%f', etc.
CROSS-REFERENCE INFORMATION
This function calls:
asciiWrite asciiWrite: Write a matrix as an ascii file
This function is called by:
asciiRead asciiRead: Read an ascii file into a matrix
asciiWrite asciiWrite: Write a matrix as an ascii file
SUBFUNCTIONS
function selfdemo
SOURCE CODE
function asciiWrite(mat, fileName, format)
% asciiWrite: Write a matrix as an ascii file
%    Usage: asciiWrite(mat, fileName, format)
%        format: format string, such as '%d', '%f', etc.
%    Roger Jang, 20041021
if nargin<1, selfdemo; return; end
if nargin<2, fileName='asciiFile.txt'; end
if nargin<3, format='%g'; end
fid = fopen(fileName, 'w');
for i = 1:size(mat,1),
    fprintf(fid, [format, ' '], mat(i, :));
    fprintf(fid, '\n');
end
fclose(fid);
% ====== Self demo
function selfdemo
x=magic(5);
fileName=tempname;
asciiWrite(x, fileName, '%d');
fprintf('The content of %s is\n', fileName);
type(fileName);