Description of mode
Home > utility > mode.m
mode
PURPOSE
mode: Mode of a vector
SYNOPSIS
function [element, index] = mode(x)
DESCRIPTION
mode: Mode of a vector
    Usage: [element, index] = mode(x)
CROSS-REFERENCE INFORMATION
This function calls:
elementCount elementCount: Count elements in a vector.
This function is called by:
figure2eps figure2eps: Save figure to eps file
split split: Split a string based on a given delimiter
SOURCE CODE
function [element, index] = mode(x)
%mode: Mode of a vector
%    Usage: [element, index] = mode(x)
%    Roger Jang, April-1-97
[sortedElement, count] = elementCount(x);
[junk, count_index] = max(count);
element = sortedElement(count_index);
index = find(x==element);