Description of strVecPrint
Home > utility > strVecPrint.m
strVecPrint
PURPOSE
strVecPrint: Print a string vector
SYNOPSIS
function strVecPrint(strVec, name)
DESCRIPTION
 strVecPrint: Print a string vector
    Usage: strVecPrint(strVec, name)
CROSS-REFERENCE INFORMATION
This function calls:
strVecPrint strVecPrint: Print a string vector
This function is called by:
split split: Split a string based on a given delimiter
strVecPrint strVecPrint: Print a string vector
SUBFUNCTIONS
function selfdemo
SOURCE CODE
function strVecPrint(strVec, name)
% strVecPrint: Print a string vector
%    Usage: strVecPrint(strVec, name)
%    Roger Jang, 20070117
if nargin<1; selfdemo; return; end
fprintf('%s = {', name);
if length(strVec)==0
    fprintf('}\n');
    return;
end
fprintf('''%s''', strVec{1});
for i=2:length(strVec)
    fprintf(', ''%s''', strVec{i});
end
fprintf('}\n');
% ====== Self selfdemo
function selfdemo
myStrVec={'abc','mn','xyz'};
strVecPrint(myStrVec, 'myStrVec');