<%@language=JScript%>
<%title="Utility Toolbox"%>
<script>
title="Utility Toolbox";
</script>
<html>
<head>
	<title>Utility Toolbox</title>
	<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=big5">
	<meta HTTP-EQUIV="Expires" CONTENT="0">
</head>

<body>
<h2 align=center><script>document.write(title)</script></h2>
<h3 align=center><a target=_blank href="/jang">Roger Jang</a></h3>
<hr>

<!== 簡要說明 -->
<h3>Introduction</h3>
<blockquote>
This toolbox provide commonly used utility functions. If you want to download the whole toolbox, please click <a href="..\utility.rar">here</a>. The toolbox is required for some of my other toolboxes:
<ul>
<li><a target=_blank href="../machineLearning">Machine Learning Toolbox</a>
<li><a target=_blank href="../sap">Speech & Audio Processing Toolbox</a>
<li><a target=_blank href="../asr">ASR (Automatic Speech Recognition) Toolbox</a>
</ul>
<p>If you are using the toolbox for your research, please kindly give reference to the toolbox as follows: 
<br><b>
Jyh-Shing Roger Jang, "Utility Toolbox", available from the link at the author's homepage at "http://mirlab.org/jang". 
</b>

</blockquote>

<!== 列出函數 -->
<!--
<h3>Documentation</h3>
<blockquote>
Here are some docs of the toolbox:
<ul>
<li><a target=_blank href="html/index.html">Document generated by m2html</a>
</ul>
</blockquote>
-->

<hr>
<script language="JavaScript">
document.write("Last updated on " + document.lastModified + ".")
</script>

</body>
</html>