function feaObj=feaRead(feaFile, plotOpt)
% feaRead: Read the feature file generated by hcopy of HTK
%	Usage:
%		feaObj=feaRead(feaFile, plotOpt)
%
%	Example:
%		feaFile='test.fea';
%		feaObj=feaRead(feaFile, 1);
%		fprintf('feaObj.frameNum = %d\n', feaObj.frameNum);
%		fprintf('feaObj.samplePeriod = %d\n', feaObj.samplePeriod);
%		fprintf('feaObj.sampleBytes = %d\n', feaObj.sampleBytes);
%		fprintf('feaObj.paramKind = %d\n', feaObj.paramKind);

%	Roger Jang, 20050303, 20111006

if nargin<1, selfdemo; return; end
if nargin<2, plotOpt=0; end

% ====== Get the right endian
[platform, maxSize, endian]=computer;
if endian=='L', machineFormat='l'; end
if endian=='B', machineFormat='b'; end
fid=fopen(feaFile, 'rb');
frameNum=fread(fid, 1, 'int32');

feaObj.frameNum=fread(fid, 1, 'int32');
feaObj.samplePeriod=fread(fid, 1, 'int32');
feaObj.sampleBytes=fread(fid, 1, 'int16');
feaObj.paramKind=fread(fid, 1, 'int16');

if feaObj.frameNum<0 || feaObj.samplePeriod<0 || feaObj.sampleBytes<0 || feaObj.paramKind<0
	if endian=='L', machineFormat='b'; end
	if endian=='B', machineFormat='l'; end
end
fclose(fid);

% ====== Use the right machine format to read the file again
fid=fopen(feaFile, 'rb');
feaObj.frameNum=fread(fid, 1, 'int32', 0, machineFormat);
feaObj.samplePeriod=fread(fid, 1, 'int32', 0, machineFormat);
feaObj.sampleBytes=fread(fid, 1, 'int16', 0, machineFormat);
feaObj.paramKind=fread(fid, 1, 'int16', 0, machineFormat);
feaObj.feaDim=feaObj.sampleBytes/4;
%fprintf('frameNum=%d, samplePeriod=%d, sampleBytes=%d, paramKind=%d, feaDim=%d\n', feaObj.frameNum, feaObj.samplePeriod, feaObj.sampleBytes, feaObj.paramKind, feaObj.feaDim);
mfcc0=fread(fid, inf, 'float32', 0, machineFormat);
feaObj.feature=reshape(mfcc0, feaObj.feaDim, length(mfcc0)/feaObj.feaDim);
fclose(fid);

if plotOpt
	surf(feaObj.feature);
	box on; rotate3d on
end

% ====== Self demo
function selfdemo
mObj=mFileParse(which(mfilename));
strEval(mObj.example);
