function feaWrite(feaObj, feaFile)
% feaRead: Read the feature file generated by hcopy of HTK
%	Usage:
%		feaObj=feaRead(feaFile, plotOpt)
%
%	Example:
%		feaFile='test.fea';
%		feaObj=feaRead(feaFile, 1);
%		feaWrite(feaObj, 'test02.fea');

%	Roger Jang, 20050303, 20111006

if nargin<1, selfdemo; return; end
if nargin<2, plotOpt=0; end

machineFormat='b';
fid=fopen(feaFile, 'w');
fwrite(fid, feaObj.frameNum, 'int32', 0, machineFormat);
fwrite(fid, feaObj.samplePeriod, 'int32', 0, machineFormat);
fwrite(fid, feaObj.sampleBytes, 'int16', 0, machineFormat);
encoded=dec2bin(feaObj.paramKind);
if length(encoded)>12 &&  encoded(end-12)=='1'
	feaObj.paramKind=feaObj.paramKind-4096;  %Since we don't write CRC...
end
fwrite(fid, feaObj.paramKind, 'int16', 0, machineFormat);
fwrite(fid, feaObj.feature(:), 'float32', 0, machineFormat);
fclose(fid);

% ====== Self demo
function selfdemo
mObj=mFileParse(which(mfilename));
strEval(mObj.example);
