<!%@language=JScript%>
<!%title="Speech and Audio Processing Toolbox"%>
<script>title="Speech and Audio Processing (SAP) Toolbox</script>
<script>
title="Speech and Audio Processing Toolbox";
</script>
<html>
<head>
	<title>Speech and Audio Processing Toolbox</title>
	<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=big5">
	<meta HTTP-EQUIV="Expires" CONTENT="0">
</head>

<body>
<h2 align=center><script>document.write(title)</script></h2>
<h3 align=center><a target=_blank href="/jang">Roger Jang</a></h3>
<hr>

<!== 簡要說明 -->
<h3>Introduction</h3>
<blockquote>
This toolbox provide MATLAB functions for speech and audio signal processing. Click <a href="..\sap.rar">here</a> to download the toolbox.
<p>
Before using the toolbox, you should add the following toolboxes to your search path:
<ul>
<li><a target=_blank href="../utility">Utility Toolbox</a>
</ul>
<p>If you are using the toolbox, please kindly give reference as follows: 
<br><b>
Jyh-Shing Roger Jang, "Speech and Audio Processing (SAP) Toolbox", available at "<a href="/jang/matlab/toolbox/sap">http://mirlab.org/jang/matlab/toolbox/sap</a>". 
</b>

</blockquote>

<h3>Documentation</h3>
<ul>
<li><a target=_blank href="/jang/books/audioSignalProcessing">On-line tutorial of "Audio Signal Processing and Recognition"</a> using the toolbox, with numerous working examples.
<!--<li><a target=_blank href="html/index.html">Toolbox document generated by m2html</a>-->
</ul>

<hr>
<script language="JavaScript">
document.write("Last updated on " + document.lastModified + ".")
</script>

</body>
</html>